Repository retaildevcrews/asb-spark, pull requests merged in 2021-07, with the labels that each got.

#20 Updates from train-the-coach
  README.md
  networking/hub-default.json
  networking/hub-regionA.json
  networking/spoke-BU0001A0008.json
Labels: Documentation, Spark

#21 Train-the-Coaches update
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/docker.yaml
  README.md
Labels: Documentation, Spark

#22 added azure policy section
  README.md
Labels: Documentation, InternalFeedback, Spark

#23 Remove "ngsa" namespace from container image policy "excludedNamespaces" list
  cluster-stamp.json
  gitops/ngsa/ngsa-memory.yaml
Labels: InternalFeedback, Spark

#25 Added do not update message
  README.md
Labels: Spark, TechnicalDebt
