Repository retaildevcrews/asb-spark, pull requests merged in 2021-06, with the labels that each got.

#2 removed unused content
  README-AIRS.md
  README.md
  airs-cleanup.sh
  airs-setup.sh
  cleanup.sh
  docs/HackGuide.md
  setup.sh
Labels: Spark

#3 added ghcr.io challenge
  .devcontainer/post-install.sh
  challenges/README.md
  challenges/github-container-registry/README.md
  challenges/github-container-registry/ngsa-ghcr.yaml
  cluster-stamp.json
  networking/hub-regionA.json
  saveenv.sh
  setup.sh
Labels: Challenge, Spark

#4 Add links to asb videos from upskilling hack to the hack guide
  docs/HackGuide.md
Labels: Documentation, Sharing

#8 GitHub Action to add DNS records for hack participants
  .github/workflows/README.md
  .github/workflows/create-dns-record.sh
  .github/workflows/dns.yml
  README.md
Labels: Spark

#9 Create limited custom role for github action
  .github/workflows/README.md
  .github/workflows/create-dns-record.sh
Labels: Spark

#10 added code owners file
  .github/CODEOWNERS
Labels: Spark

#11 updated readme
  README.md
  cloudshell.txt
  gitops/cluster-baseline-settings/01-namespace.yaml
  gitops/ingress/01-namespace.yaml
Labels: DevExperience, Documentation, Spark

#13 updated ACR challenge
  README.md
  challenges/azure-container-registry/README.md
  challenges/azure-container-registry/ngsa-ghcr.yaml
  challenges/github-container-registry/README.md
  docs/EngineeringPractices.md
  docs/NamingConvention.md
Labels: Challenge, Spark

#12 Challenge 4 - deploy loderunner
  .devcontainer/Dockerfile
  README.md
  challenges/README.md
  challenges/deploy-WebV/README.md
  challenges/deploy-WebV/images/log-analytics-1.PNG
Labels: Challenge, InternalFeedback, Sharing, Spark

#16 updated hack guide
  docs/HackGuide.md
Labels: Documentation, Spark

#17 use webv 2.0 release
  .devcontainer/Dockerfile
Labels: Spark

#19 Fix linkage to challenge markdowns
  README.md
Labels: Bug, Challenge

#18 removed setup.sh
  docs/cloudshell.txt
  setup.sh
Labels: Documentation, Spark
